name: badley

services:
  postgres:
    image: postgres:latest
    container_name: badley_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: badley_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
